Add M5Stick C Plus
esphome/esphome-devices pull request #536
Opened 2023-10-16 21:40 UTC by landonr

2023-10-16 21:58 UTC, jesserockz requested changes

2023-10-16 21:58 UTC, jesserockz commented on src/docs/devices/M5Stack-M5StickC-PLUS/index.md
> +project-url: https://github.com/martydingo/esphome-axp192
While this is a part of it, I wouldn't say its the project-url...
Might be better to link to m5stack official doc page for this device

2023-10-17 05:46 UTC, landonr commented on src/docs/devices/M5Stack-M5StickC-PLUS/index.md
> +project-url: https://docs.m5stack.com/en/core/m5stickc_plus
updated to the docs urlupdated to the docs url

2023-10-18 03:45 UTC, jesserockz approved these changes

2023-10-18 03:45 UTC, merged