Add Apollo Automation Devices
esphome/esphome-devices pull request #638
Opened 2024-01-25 05:17 UTC by Bunton33

2024-01-26 00:24 UTC, manafount reviewed
Looking good so far! I left a few comments about some minor styling stuff, but I didn't find anything that needed a major correction. You may want to call out the optional sensors in the list of components for clarity, though (ex: `(Optional) MiCS-4514 ...`)

Reading through some other device pages, it looks like Github-flavor markdown is generally supported. If you're looking for ideas for styling, there's a good doc available [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

2024-01-26 00:24 UTC, manafount commented on src/docs/devices/Apollo-Automation-AIR-1/index.md
> +![Apollo AIR-1](Apollo-AIR-1.jpg "Apollo AIR-1")
I'd suggest putting one of the product images at the top so that it displays above the fold for people just browsing through device lists.

Keeping the rest at the bottom seems fine to me, though. But maybe add a "Product Images" header so that it shows up as a quick navigation option:

```md
## Product Images
![Apollo AIR-1](Apollo-AIR-1.jpg "Apollo AIR-1")
```

2024-01-26 00:24 UTC, manafount commented on src/docs/devices/Apollo-Automation-MSR-1/index.md
> +![Apollo MSR-1](Apollo-MSR-1.jpg "Apollo MSR-1")
Same suggestion here: move one of the images above the fold, and add a Product Images header for any others that are added.

2024-01-26 00:24 UTC, manafount commented on src/docs/devices/Apollo-Automation-AIR-1/index.md
> +
Adding headers (`## Header Text`) to your markdown will generate quick navigation links on the right side (for desktop browsers) and allow linking to each section by hash/location keys. Possible headers based on the current markdown content might be:

## Description

The Apollo Automation AIR-1 is an air quality sensor with (...)

## Components
(...)

## External Links
(...)

2024-01-26 00:24 UTC, manafount commented on src/docs/devices/Apollo-Automation-AIR-1/index.md
> +- SEN55 PM1, PM2.5, PM4, PM10, VOC, NOx, Temperature and Humidity
For the sensor list, I think it'd be cool to link to the ESPHome documentation for that specific sensor. Another option would be an official product page or datasheet, but I think the ESPHome implementation details for that sensor would be more relevant.

Just a thought, though!

2024-01-26 00:24 UTC, manafount commented on src/docs/devices/Apollo-Automation-MSR-1/index.md
> +The Apollo Automation MSR-1 is a mmWave CO2 multisensor with the following features:
(same suggestion as above regarding headers for distinct sections for readability/navigation)

2024-07-04 00:54 UTC, kbx81 requested changes

2024-07-04 00:54 UTC, kbx81 commented on src/docs/devices/Apollo-Automation-AIR-1/index.md
> +date-published: 2024-06-24
```suggestion
date-published: 2024-07-03
```

2024-07-04 00:54 UTC, kbx81 commented on src/docs/devices/Apollo-Automation-MSR-1/index.md
> +date-published: 2024-06-24
```suggestion
date-published: 2024-07-03
```

2024-07-04 00:54 UTC, kbx81 commented on src/docs/devices/Apollo-Automation-MSR-2/index.md
> +date-published: 2024-06-24
```suggestion
date-published: 2024-07-03
```

2024-07-04 00:54 UTC, kbx81 commented on src/docs/devices/Apollo-Automation-MTR-1/index.md
> +date-published: 2024-06-24
```suggestion
date-published: 2024-07-03
```

2024-07-04 00:55 UTC, kbx81 approved these changes

2024-07-04 00:58 UTC, merged