polished sonoff th10 documentation
esphome/esphome-devices pull request #859
Opened 2024-10-09 19:29 UTC by reogaro

I reworked and corrected the Sonoff TH10 documentation, and added some notes on its almost-identical bigger brother, the TH16.

Please be nice, this is my first pull request.

## Type of changes

- [ ] New device
- [x] Update existing device
- [ ] Removing a device
- [x] General cleanup
- [ ] Other

## Checklist:

- [x] There are no passwords or secrets references in any examples. 
      The only exceptions are `!secret wifi_ssid` and `!secret wifi_password`.
- [x] The `wifi` or `ethernet` block has no static / manual ip address specified.
- [x] The first configuration provided should be **hardware definitions only**.
      A more involved example can be provided in a separate configuration block.

2024-10-10 20:19 UTC, jesserockz requested changes
A few suggestions below and will need more manual changes to align ids too

2024-10-10 20:19 UTC, jesserockz commented on src/docs/devices/Sonoff-TH10/index.md
> +    name: "${friendly_name} WiFi Signal"
Entities should not be prefixed with friendly name substitution as it is added automatically by using `esphome` -> `friendly_name`

```suggestion
    name: WiFi Signal
```

2024-10-10 20:19 UTC, jesserockz commented on src/docs/devices/Sonoff-TH10/index.md
> +    id: TH1x_1_blue_led
IDs can be simpler
```suggestion
    id: blue_led
```

2024-10-10 20:19 UTC, jesserockz commented on src/docs/devices/Sonoff-TH10/index.md
>    board_flash_mode: dout
```suggestion

esp8266:
  board: esp01_1m
```

2024-10-22 17:26 UTC, reogaro commented
I did the requested changes - is this up to spec?

2024-11-09 13:35 UTC, merged